services:
  hytale:
    image: ak474000/hytale-docker-server
    tty: true
    stdin_open: true
    ports:
      - "5520:5520/udp"
    environment:
      - MEMORY=8G
    volumes:
      - Path/On/Host:/data
      #- /etc/machine-id:/etc/machine-id:ro
    restart: unless-stopped
